### PR TITLE
Serial effects

### PR DESCRIPTION
**Pull request by mazz**
run effects serially as stated in challenge. buffer > player > distortion > reverb > defaultmixer

### CODE REVIEW

**Comment by robotlovesyou** [comment]
Hi, I really appreciate you updating the project to the latest swift syntax but I'm a bit confused about what you are trying to achieve with the second commit. The point of the project (see [https://www.robotlovesyou.com/mixing-between-effects-with-avfoundation/#header](https://www.robotlovesyou.com/mixing-between-effects-with-avfoundation/#header)) is to mix _between_ two different  audio effects. With the changes you've made, won't it just have both effects on all the time and simply fade the audio in and out?

**Comment by mazz** [comment]
Reject the second PR if you think it's no good. The idea was to implement the first item in your "What's Next" section on the blog:

"Here are some ideas for you to try out next

Pass the output of one effect into the other before sending it to the output instead of mixing them together using the mixer."

**Comment by robotlovesyou** [comment]
OK. I'm going to reject it because if I accept it then the code in the repo is no longer related to the blog post.

**Comment by robotlovesyou** [comment]
Just for clarity by the way, I think it's **awesome** that you went ahead and coded one of the follow up tasks, I just don't think that the repository for code relating to the blog post is an appropriate place for it because the repo would no longer match the post. Perhaps your own github would be a more appropriate spot?

**Comment by mazz** [comment]
You're very welcome! Thank you for your original post. It got me back into CoreAudio and using Swift. 

Can you do me a favour? I'm experimenting with your code by trying to implement real-time changing of effects. My idea is to change the routing of the nodes on-the-fly. For instance, if I have 

Player > decimated > radio tower > mixer output

And I want to dynamically remove the impact Decimated on the mix, I update the graph to:

Player > radio tower > mixer output 

My attempts so far are fruitless(audio silence) and no error message (one of the most infuriating things about CoreAudio). If you care to, take a look at:

https://github.com/mazz/AudioMixerDemo/tree/disable_decimated

Which is an example of what I've tried so far!

**Pull request closed without merging**
