### PR TITLE
Create Updated to swift 4

### PR DESCRIPTION
**Pull request by wenh08**
Hi! I came across your AudioMixDemo and I've updated this project to be a working version to the latest Xcode 13, along with swift 4. This code is now in working format :)

### CODE REVIEW

**Comment by wenh08** [comment]
Demo has been updated to the latest Swift 4 version

**Comment by robotlovesyou** [comment]
Hi. It's great that you did this but given that the repository contains the clear message 
### This code is very old and no longer maintained. It may work, it may not but I've no intention of updating it any time soon!
I won't be spending the time to validate or merge it. I don't even have XCode on my machine at the moment, just the CLI tools. 

Please feel free to share your working version though

**Comment by wenh08** [comment]
Hi, how can I share the working version? I tried to make a pull request but
I dont have the access

**Comment by robotlovesyou** [comment]
Just fork the repository to your own account and then apply your update
there.

**Pull request closed without merging**
